common:
  server-name: consumer-service


server:
  port: 14512
spring:
  application:
    name: ${common.server-name}
  main:
    allow-bean-definition-overriding: true
dubbo:
  application:
    name: ${common.server-name}
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: 15511

