common:
  server-name: consumer-service


server:
  port: 8088
spring:
  application:
    name: ${common.server-name}
  main:
    allow-bean-definition-overriding: true
dubbo:
  application:
    name: ${common.server-name}
  registry:
    address: nacos://192.16.1.83:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: 15511

